# Generated by Django 2.2.18 on 2021-04-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badsides',
            new_name='Badside',
        ),
        migrations.RenameModel(
            old_name='Goodsides',
            new_name='Goodside',
        ),
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
